quarkus.artemis."artemis".username=admin
quarkus.artemis."artemis".password=admin
quarkus.artemis."artemis".url=tcp://localhost:61616

quarkus.pooled-jms.transaction=xa

quarkus.transaction-manager.default-transaction-timeout=10s
quarkus.transaction-manager.enable-recovery=true

ibmmq.channel=DEV.ADMIN.SVRCONN
ibmmq.hostname=localhost
ibmmq.password=app
ibmmq.port=1414
ibmmq.queue-manager=LOCALDEVQM
ibmmq.user=app
